twig:
  file_name_pattern: "*.twig"
  form_themes: ["bootstrap_4_layout.html.twig"] #con esto ya se tendran estilos por defec, pero solo a los que se renderizan con form

when@test:
  twig:
    strict_variables: true
